name: wallpaperhub
description: A Beautiful Wallpaper App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  dio: ^4.0.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  flutter_cache_manager: ^3.3.0
  flutter_scroll_to_top: ^2.1.1
  font_awesome_flutter: ^9.2.0
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  http: ^0.13.1
  image_gallery_saver: ^1.6.9
  permission_handler: ^7.1.0
  sizer: ^2.0.13
  splash_screen_view: ^3.0.0
  url_launcher: any
  wallpaper_manager: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/splash_logo.png
    - images/search.png
    - images/User_avatar.png
    - images/appbar_logo.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
    - family: Langer
      fonts:
        - asset: assets/fonts/Langar-Regular.ttf

splash_screen_view:

  color: "#ffffff"
